### ISSUE TITLE
"DISCONNECTE FROM THE SERVER - RELOAD"

### ISSUE THREAD

**Issue by pellicano-lab** [dcousin3/superb#6]
Dear Responsible,
dear Community,

I filled in the steps required to perform the superb online graphic interface _https://dcousin3.shinyapps.io/superbshiny/;
when I click to apply step 5, something goes wrong and the following message is presented:

"DISCONNECTED FROM THE SERVER - RELOAD"

Once I reload, of course, the forms are all empty and I have to restart everithing from the beginning. I repeated the operation over and over but the problem is always there.

Can you help me?

Best regards 

AP

**Comment by dcousin3** [comment]
Thank you for raising this issue. It was related to R's new handling of && vs. &.

It is now solved. Please reinstall `superb` from its github repository then launch `superbShiny( )` for the graphical interface with the following instructions:

```
devtools::install_github("dcousin3/superb")
library(superb)
superbShiny()
```

The CRAN team is currently on vacation (August 11th, 2024) until the 16th, so I won't be able to update the CRAN version and the shinyapps.io online version until then. Sorry about this.

Sincerely,
Denis.

**Comment by pellicano-lab** [comment]
Dear Denis,
Thank you very much!
I installed packages but unfortunately, I 'm not an R user and I cannot operate text code.
I'll be waiting for august 16th .

Best regards!

Antonello

________________________________

**Comment by dcousin3** [comment]
If you run these two lines of code, the graphical interface will show up
in your browser. From that point, there is no need to program anything
else. It is the exact same graphical interface as the one you would
obtain with shinyapp.io.


```
library(superb)
superbShiny()
```

**Comment by pellicano-lab** [comment]
Dear Denis,

Thanks again.

I managed to open the graphical interface; however, it still crashes at the end of step 5.
I attach the screenshot.

Best,

Antonello

________________________________

**Comment by dcousin3** [comment]
Hello,

I do not see the screen capture; however, can you check in the lower left corner the version of the app: you should see 3.5
![ScreenCapture](https://github.com/user-attachments/assets/f526271c-38c0-488f-8661-6db356509d32)

If that is not the case, installation of the most recent version of "superb" did not succeed.

You can use my personal email (denis.cousineau@uottawa.ca) to continue the discussion, I hope to be able to help you with this.

Denis.
